INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (1, 'Celular 5g', 1899.0, 12, 5, 1);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (2, 'Arroz 5kg', 24.9, 45, 20, 2);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (3, 'Papel Toalha', 2.65, 62, 20, 3);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (4, 'Pão de Forma', 6.85, 45, 20, 4);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (5, 'Água Mineral 1L', 3.9, 111, 50, 5);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (6, 'TV Led 32"', 1499.0, 9, 5, 1);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (7, 'Feijão Preto 1kg', 8.9, 64, 30, 2);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (8, 'Sabonete Líquido', 12.9, 41, 15, 3);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (9, 'Leite Integral 1L', 4.1, 154, 50, 5);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (10, 'Queijo Muçarela', 49.0, 18, 10, 4);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (11, 'PlayStation 5', 7990.0, 5, 10, 1);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (12, 'Farinha de Trigo 1kg', 3.49, 152, 100, 2);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (13, 'Detergente Neutro', 4.9, 29, 50, 3);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (14, 'Bolo Formigueiro', 7.5, 14, 10, 4);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (15, 'Suco de Uva 1L', 13.9, 52, 40, 5);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (16, 'Barbeador Recarregável', 179.0, 5, 5, 1);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (17, 'Fubá Especial 1kg', 3.75, 37, 40, 2);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (18, 'Vassoura de Pelo', 21.9, 16, 15, 3);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (19, 'Pó de café 500g', 8.5, 45, 40, 4);
INSERT INTO Produtos (IdProduto, Nome, Preco, EstoqueAtual, EstoqueMinimo, IdCategoria) VALUES (20, 'Refrigerante Cola 2L', 4.9, 53, 40, 5);